### ISSUE TITLE
any plan to migrate the code the torch of open-source version?

### ISSUE THREAD

**Issue by SeekPoint** [jiweil/Neural-Dialogue-Generation#4]
since the fbtorch looks 'dead', no update and failed installation, and no response of error report

**Comment by SeekPoint** [comment]
Although the lua is new to me, I figured out the migration

**Comment by suragnair** [comment]
@loveJasmine could you share how you did it?

**Comment by SeekPoint** [comment]
@suragnair 

some change like:

 local model={}
-local base_model=torch.reload("../../Decode/decode_model")
+local base_model=paths.dofile('../../Decode/decode_model.lua')

-    self.generate_model=torch.reload("./generative")
+    self.generate_model=paths.dofile('generative.lua')


-require "fbtorch"
-local params=torch.reload("./parse")
-local model=torch.reload("./model")
+
+--require "fbtorch"
+--local params=torch.reload("./parse")
+--local model=torch.reload("./model")
+local params=paths.dofile('parse.lua')
+local model=paths.dofile('model.lua')


see above, I guess you can figure it out;)
